# Generated by Django 5.0.6 on 2024-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
